version: "3.7"

services:
  tcc-manager:
    container_name: tcc-manager-api
    build:
      context: .
      target: development
    command: sh -c "npx prisma generate && npx prisma migrate dev && npm ci && npm run start:dev"
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root:root@mysql:3306/tcc_manager
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend
  mysql:
    container_name: mysql
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=tcc_manager
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: "bridge"

