version: "3.7"

services:
  tcc-manager:
    container_name: tcc-manager-api
    build:
      context: .
      target: development
    command: sh -c "npm ci && npx prisma generate && npx prisma migrate dev && npm run start:dev"
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://root:root@postgres:5432/tcc_manager
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=tcc_manager
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - backend

networks:
  backend:
    driver: "bridge"

